image:
  file: .gitpod.Dockerfile

ports:
  # Rails server
  - port: 3000
    onOpen: open-preview
  # PostgreSQL server
  - port: 5432
    onOpen: ignore

tasks:
  - init: >
      BUNDLE_FROZEN=true bundle install &&
      rake db:create &&
      yarn
    command: >
      rails server
